apiVersion: v1
kind: Service
metadata:
  name: beerpub
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: beer
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beerpub
  labels:
    app: beer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: beer
  template:
    metadata:
      labels:
        app: beer
    spec:
      containers:
        - name: beerpub
          image: "127.0.0.1:30400/beerpub:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
